MACRO(INSTALL_FILES_RECURSIVE DESTINATION FILE_LIST)

    FOREACH(FILE ${${FILE_LIST}})
        STRING(REGEX MATCH "(.*)[/\\]" DIR ${FILE})
        INSTALL(FILES ${FILE} DESTINATION ${DESTINATION}/${DIR})
    ENDFOREACH()

ENDMACRO()
